services:

  postgres:
    image: postgres:latest
    container_name: postgres-taskmaster
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: taskmaster_database
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - taskmaster-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak-taskmaster
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - taskmaster-network
    command:
      - "start-dev"

  mail-dev:
    image: maildev/maildev
    container_name: mail-taskmaster
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - taskmaster-network
    restart: unless-stopped

volumes:
  postgres:
    driver: local

networks:
  taskmaster-network:
    driver: bridge