@startuml
'https://plantuml.com/class-diagram

class Task {
    -id: Integer
    -title: String
    -description: String
    -dueDate: LocalDateTime
    -status: TaskStatus
    -priority: TaskPriority
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String
}

class TaskAttachment{
    -id: Integer
    -taskId: Integer
    -path: String
    -type: String
    -size: Integer
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String

}

class TaskComment{
    -id: Integer
    -taskId: Integer
    -comment: String
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String
}

enum TaskStatus {
    TODO
    IN_PROGRESS
    COMPLETED
    ARCHIVED
}

enum TaskPriority {
    LOW
    MEDIUM
    HIGH
}

enum TaskAttachmentType {
    IMAGE
    VIDEO
    AUDIO
    DOCUMENT
    FILE
}

TaskStatus <|- Task
TaskPriority <|- Task
TaskAttachmentType <|- TaskAttachment

Task "1" *-- "0.*" TaskAttachment
Task "1" *-- "0.*" TaskComment

@enduml