@startuml
'https://plantuml.com/class-diagram


class BaseEntity {
    -id: Integer
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String
}

class Task {
    -id: Integer
    -title: String
    -description: String
    -dueDate: LocalDateTime
    -status: TaskStatus
    -priority: TaskPriority
    -archived: boolean
    -category: Category
}

class Category {
    -id: Integer
    -name: String
    -description: String
    -createdAt: LocalDateTime
    -createdBy: String
}

enum TaskStatus {
    PENDING
    IN_PROGRESS
    DONE
}

enum TaskPriority {
    LOW
    MEDIUM
    HIGH
}

BaseEntity <|---- Task
Category "1"<---->"N" Task
TaskStatus <|- Task
TaskPriority <|- Task

@enduml