@startuml
'https://plantuml.com/class-diagram

class Task {
    -id: Integer
    -title: String
    -description: String
    -dueDate: LocalDateTime
    -status: TaskStatus
    -priority: TaskPriority
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String
}

class TaskComment{
    -id: Integer
    -taskId: Integer
    -comment: String
    -createdAt: LocalDateTime
    -createdBy: String
    -lastModified: LocalDateTime
    -lastModifiedBy: String
}

enum TaskStatus {
    TODO
    IN_PROGRESS
    COMPLETED
    ARCHIVED
}

enum TaskPriority {
    LOW
    MEDIUM
    HIGH
}


TaskStatus <|- Task
TaskPriority <|- Task


Task "1" *-- "0.*" TaskComment

@enduml