spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  banner:
    location: banner-prod

  application:
    name: Taskmaster

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    filter: true
    operations-sorter: method
  show-actuator: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/management-server
  endpoint:
    health:
      show-details: always