spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskmaster_database
    username: username
    password: password

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  banner:
    location: banner

  application:
    name: Taskmaster

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/taskmaster
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          principal-name: email

  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    filter: true
    operations-sorter: method
  show-actuator: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/management-server
  endpoint:
    health:
      show-details: always