spring:

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: missing
    username: missing
    password: missing

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  banner:
    location: banner-test

  application:
    name: Taskmaster

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: missing
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH
    allowed-headers: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    filter: true
    operations-sorter: method
  show-actuator: true
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1/management-server
  endpoint:
    health:
      show-details: always